Example on how to create Opsgenie Incident and Argo Workflow
port-labs/port-agent pull request #19
Opened 2024-01-10 08:45 UTC by mk-armah

# Description

What 
- Added example on how to create an opsgenie incident
- Added example on how to trigger the submission of an argo workflow

## Type of change

Please leave one option from the following and delete the rest:

- [ ] New feature (non-breaking change which adds functionality)

2024-01-17 14:01 UTC, PeyGis commented on README.md
> +This example helps internal developer teams to trigger [Opsgenie](https://www.atlassian.com/software/opsgenie) job using Port's self service actions. In particular, you will create a blueprint for `o
"... to trigger [Opsgenie](https://www.atlassian.com/software/opsgenie) job"

I think it should be incident instead of job

Also
"...to control the payload and trigger your Windmill job"
Do you mean Opsgenie incident?

2024-01-17 14:03 UTC, PeyGis commented on README.md
> +Create the following blueprint, action and mapping to trigger a Obsgenie incident.
Obsgenie incident.
 
 Typo in Opsgenie

2024-01-17 14:04 UTC, PeyGis commented on README.md
> +          "title": "message",
First letter of message should be capitalized

2024-01-17 14:05 UTC, PeyGis commented on README.md
> +          "maxLength": 130
Does the Opsgenie API require a limit on the length of the incident message?

2024-01-17 14:06 UTC, PeyGis commented on README.md
> +          "title": "description",
First letter of description should be capitalized

2024-01-17 14:06 UTC, PeyGis commented on README.md
> +          "title": "details",
First letter of details should be capitalized

2024-01-17 14:06 UTC, PeyGis commented on README.md
> +          "title": "priority",
First letter of priority should be capitalized

2024-01-17 14:07 UTC, PeyGis commented on README.md
> +        "details",
Can you also update the blueprint schema to include `details` and `priority`?

2024-01-17 14:09 UTC, PeyGis commented on README.md
> +		"message": "\"Incident Triggered via Port\"",
Why are you not passing the message and description from Port?

.payload.entity.properties.message
.payload.entity.properties.description

2024-01-24 19:00 UTC, mk-armah commented on README.md
> +          "maxLength": 130
yes

2024-01-26 09:24 UTC, PeyGis requested changes
LGTM. Requested some minor changes

2024-01-26 09:24 UTC, PeyGis commented on README.md
> +    "title": "trigger_argo_workflow",
Title should be `Trigger Argo Workflow`

2024-01-26 09:24 UTC, PeyGis commented on README.md
> +      "url": "https://l127.0.0.1:2746",
Seem to be a typo in the url (the first `l `before 127)

Also, some clients may not have their workflow at localhost so you can instead use a placeholder <enter host url>

2024-01-26 09:24 UTC, PeyGis commented on README.md
> +		"status": "if .response.statusCode == 200 then \"SUCCESS\" else \"FAILURE\" end"
is it also possible to report the runLink back to Port?

2024-01-26 09:26 UTC, mk-armah commented on README.md
> +      "url": "https://l127.0.0.1:2746",
is  example.com okay ?

2024-01-26 09:30 UTC, mk-armah commented on README.md
> +      "url": "https://l127.0.0.1:2746",
or should i go with https://{your-argo-workflow-domain}.com

2024-01-26 09:32 UTC, mk-armah commented on README.md
> +		"status": "if .response.statusCode == 200 then \"SUCCESS\" else \"FAILURE\" end"
I'll see to that

2024-01-26 10:45 UTC, PeyGis commented on README.md
> +      "url": "https://l127.0.0.1:2746",
Yeah or

<enter your argo workflow host>

2024-02-04 14:00 UTC, MPTG94 requested changes
Please resolve my comments and any other currently non-resolved comments

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +This example helps internal developer teams to trigger [Opsgenie](https://www.atlassian.com/software/opsgenie) incident using Port's self service actions. In particular, you will create a blueprint f
```suggestion
This example helps internal developer teams to trigger [Opsgenie](https://www.atlassian.com/software/opsgenie) incidents using Port's self service actions. In particular, you will create a blueprint for `opsgenieIncident` that will be connected to a backend action. You will then add some configuration files (`invocations.json`) to control the payload and trigger your Opsgenie incident directly from Port using the sync execution method.
```

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +Create the following blueprint, action and mapping to trigger a Obsgenie incident.
```suggestion
Create the following blueprint, action and mapping to trigger a Opsgenie incident.
```

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +          "type": "string"
Is there an option to define custom priorities?

If not, since there is a limited option for values, change this to an enum and make the priorities, the available values for the input

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +          "description": "Description field of the incident that is generally used to provide a detailed information about the incident",
```suggestion
          "description": "Description field of the incident that is generally used to provide detailed information about the incident",
```

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +	  "url": "\"https://api.opsgenie.com/v1/incidents/create\"",
Why type the URL again and not just take it from the action definition itself?

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +This example helps internal developer teams to submit an [Argoworkflow](https://argoproj.github.io/workflows/) using Port's self service actions. In particular, you will create a blueprint for `argoW
```suggestion
This example helps internal developer teams to submit an [Argo Workflow](https://argoproj.github.io/workflows/) using Port's self service actions. In particular, you will create a blueprint for `argoWorkflow` that will be connected to a backend action. You will then add some configuration files (`invocations.json`) to control the payload and submit your Argo Workflow directly from Port using the sync execution method.
```

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +Create the following blueprint, action and mapping to trigger the submition of a workflow.
```suggestion
Create the following blueprint, action and mapping to trigger the submission of a workflow.
```

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +    "link": "env.ARGO_WORKFLOW_HOST as $baseUrl | .payload.properties.namespace as $namespace | $baseUrl + \"/api/v1/workflows/\"+ $namespace"
Will this link take the user to the specific workflow run that was triggered?

2024-02-04 14:00 UTC, MPTG94 commented on README.md
> +    --set env.secret.ARGO_WORKFLOW_HOST=YOUR_ARGO_WORKFLOW_HOST \
This field needs more of an example, to avoid different cases where the user provides the complete API URL, or if he adds a trailing slash that shouldn't be there, etc

2024-02-06 10:08 UTC, mk-armah commented on README.md
> +    "link": "env.ARGO_WORKFLOW_HOST as $baseUrl | .payload.properties.namespace as $namespace | $baseUrl + \"/api/v1/workflows/\"+ $namespace"
Its actually the api link of the workflow

2024-02-06 19:14 UTC, mk-armah commented on README.md
> +    "link": "env.ARGO_WORKFLOW_HOST as $baseUrl | .payload.properties.namespace as $namespace | $baseUrl + \"/api/v1/workflows/\"+ $namespace"
I've added a direct link to the specific workflow that was submitted

2024-02-07 13:11 UTC, MPTG94 requested changes
Please fix my latest comment

2024-02-07 13:11 UTC, MPTG94 commented on README.md
> +        "type": "array",
@mk-armah this is not good, now the priority is an array, but an incident can only have once specific priority at any given time.

This needs to be just a standard enum property with multiple options.

Like so:

```
"priority": {
        "title": "Priority",
        "description": "Priority level of the incident. Possible values are P1, P2, P3, P4 and P5. Default value is P3.",
        "icon": "OpsGenie",
        "type": "string",
        "default": "P3",
        "enum": [
          "P1",
          "P2",
          "P3",
          "P4",
          "P5"
        ],
        "enumColors": {
          "P1": "red",
          "P2": "orange",
          "P3": "yellow",
          "P4": "green",
          "P5": "green"
        }
      }
```

2024-02-07 13:46 UTC, MPTG94 approved these changes
LGTM

2024-02-07 13:46 UTC, merged