Updated Argo Workflow Example
port-labs/port-agent pull request #23
Opened 2024-02-29 21:47 UTC by mk-armah

# Description

What - updated argo workflow example from a create operation to a day 2
Why - This is best as it prevents re-entering of workflow template everything in order to trigger the workflow
How - Leverage port advanced configuration to automatically fetch workflow template from catalog

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)

2024-03-01 08:58 UTC, yairsimantov20 requested changes
Left some comments

2024-03-01 08:58 UTC, yairsimantov20 commented on README.md
> +        "type": "Argo",
Type argo?
Did you test the bp?

2024-03-01 08:58 UTC, yairsimantov20 commented on README.md
> +		"url": "env.ARGO_WORKFLOW_HOST as $baseUrl | .payload.properties.namespace as $namespace | .payload.entity.title as $workflow_name | $baseUrl + \"/api/v1/workflows/\" + $namespace + \"/\" + $workfl
Why are you working by entity title? Are you sure?

2024-03-01 08:58 UTC, yairsimantov20 commented on README.md
> +			"link": "env.ARGO_WORKFLOW_HOST as $baseUrl | $baseUrl + \"/workflows/\"+ .response.json.metadata.namespace + \"/\" +.response.json.metadata.name"
Why is there a need to pass host in env var if you asked for it in the invocation method?

2024-03-01 08:58 UTC, yairsimantov20 commented on README.md
> +			"status": "if .response.statusCode == 200 then \"SUCCESS\" else \"FAILURE\" end",
I have some questions 

- Is triggering argo workflow is a sync operation? If you run http request to execute it will it wait for the workflow to end before returning a response?


(If it isnt then are you sure the status code is 200?)


- is it possible to send http requests from argo cd to port? Its ok if not im thinking about how should the report be done

(If it is maybe we should remove the status part and let them report the status but themselves?)

2024-03-01 08:58 UTC, yairsimantov20 commented on README.md
> +    "method": "PUT"
Are you sure it is post?

https://argo-workflows.readthedocs.io/en/latest/rest-examples/

Here it says differently

2024-03-01 09:02 UTC, mk-armah commented on README.md
> +		"url": "env.ARGO_WORKFLOW_HOST as $baseUrl | .payload.properties.namespace as $namespace | .payload.entity.title as $workflow_name | $baseUrl + \"/api/v1/workflows/\" + $namespace + \"/\" + $workfl
The entity title is expected same as the worflow name, from the blueprint. Yes i am sure

2024-03-01 09:17 UTC, mk-armah commented on README.md
> +    "method": "PUT"
Its a PUT request, actually the link you provided is for submit workflow. What i've implemented is a resubmit workflow

2024-03-01 09:17 UTC, mk-armah commented on README.md
> +			"status": "if .response.statusCode == 200 then \"SUCCESS\" else \"FAILURE\" end",
I i run the http request, this is an example of the response i get with status code 200.

```
{
    "metadata": {
        "name": "hello-world-xyokg",
        "generateName": "hello-world-",
        "namespace": "argo",
        "uid": "72cf11d7-c0c2-4e55-9335-70adbe86946b",
        "resourceVersion": "647300",
        "generation": 1,
        "creationTimestamp": "2024-03-01T09:04:09Z",
        "labels": {
            "workflows.argoproj.io/creator": "system-serviceaccount-default-port",
            "workflows.argoproj.io/resubmitted-from-workflow": "hello-world-x9w5h"
        },
        "annotations": {
            "workflows.argoproj.io/pod-name-format": "v2"
        },
        "managedFields": [
            {
                "manager": "argo",
                "operation": "Update",
                "apiVersion": "argoproj.io/v1alpha1",
                "time": "2024-03-01T09:04:09Z",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:metadata": {
                        "f:annotations": {
                            ".": {},
                            "f:workflows.argoproj.io/pod-name-format": {}
                        },
                        "f:generateName": {},
                        "f:labels": {
                            ".": {},
                            "f:workflows.argoproj.io/creator": {},
                            "f:workflows.argoproj.io/resubmitted-from-workflow": {}
                        }
                    },
                    "f:spec": {},
                    "f:status": {}
                }
            }
        ]
    },
    "spec": {
        "templates": [
            {
                "name": "whalesay",
                "inputs": {},
                "outputs": {},
                "metadata": {},
                "container": {
                    "name": "",
                    "image": "docker/whalesay:latest",
                    "command": [
                        "cowsay"
                    ],
                    "args": [
                        "hello world"
                    ],
                    "resources": {}
                }
            }
        ],
        "entrypoint": "whalesay",
        "arguments": {}
    },
    "status": {
        "startedAt": null,
        "finishedAt": null,
        "nodes": {
            "hello-world-xyokg": {
                "id": "hello-world-xyokg",
                "name": "hello-world-xyokg",
                "displayName": "hello-world-x9w5h",
                "type": "Pod",
                "templateName": "whalesay",
                "templateScope": "local/hello-world-x9w5h",
                "phase": "Pending",
                "startedAt": null,
                "finishedAt": null,
                "progress": "0/1",
                "hostNodeName": "minikube"
            }
        },
        "conditions": [
            {
                "type": "Completed",
                "status": "False"
            }
        ]
    }
}
```

 and No, it doesnt wait for the workflow to complete before returning a response. what we don't get in the response status is the phase property which informs the status of the workflow (Errored/Finished ) but we do get an outright response
 
 
![image](https://github.com/port-labs/port-agent/assets/85971733/f3462429-c610-4d8b-98b1-d0c060b8589a)

![image](https://github.com/port-labs/port-agent/assets/85971733/389c9d54-fa03-4acd-83ad-d40024fe511f)

2024-03-01 09:18 UTC, mk-armah commented on README.md
> +			"link": "env.ARGO_WORKFLOW_HOST as $baseUrl | $baseUrl + \"/workflows/\"+ .response.json.metadata.namespace + \"/\" +.response.json.metadata.name"
Do you suggest i take it out please ?

2024-03-01 09:18 UTC, mk-armah commented on README.md
> +        "type": "Argo",
This was an oversight, i'll correct it

2024-03-01 09:22 UTC, yairsimantov20 commented on README.md
> +			"link": "env.ARGO_WORKFLOW_HOST as $baseUrl | $baseUrl + \"/workflows/\"+ .response.json.metadata.namespace + \"/\" +.response.json.metadata.name"
Use it from the incoming Kafka event
You can click on the payload button to see all the properties you have access to

2024-03-01 09:57 UTC, mk-armah commented on README.md
> +			"link": "env.ARGO_WORKFLOW_HOST as $baseUrl | $baseUrl + \"/workflows/\"+ .response.json.metadata.namespace + \"/\" +.response.json.metadata.name"
Its becoming a bit problematic when i want to report the link back to port, `".payload.action.invocationMethod.url` doesn't seem to work in report

2024-03-02 00:24 UTC, yairsimantov20 approved these changes
🌊

2024-03-02 00:24 UTC, merged