Remove headers from signature verification if gitlab invocation method
port-labs/port-agent pull request #29
Opened 2024-08-05 16:14 UTC by omby8888

# Description

What - Remove headers from signature verification if gitlab invocation method
Why

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

2024-08-07 08:52 UTC, Tankilevitch requested changes
I would rather add CONTRIBUTING.md on how to test it with environment variables

2024-08-07 08:52 UTC, Tankilevitch commented on app/invokers/webhook_invoker.py
>          # Remove the headers to avoid them being used in the signature verification
lets update the comment

2024-08-07 10:29 UTC, Tankilevitch commented on app/core/config.py
> +
I would do it if specific `env` variable is specified . e.g. `if ENV_RUNTIME='DEBUG'`

2024-08-07 11:53 UTC, matan84 requested changes
left 1 comment

2024-08-07 11:53 UTC, matan84 commented on app/invokers/webhook_invoker.py
> +        if not self.validate_incoming_signature(msg, invocation_method['type']):
All invocation types have a `type` property?

2024-08-07 13:52 UTC, omby8888 commented on app/invokers/webhook_invoker.py
> +        if not self.validate_incoming_signature(msg, invocation_method['type']):
yeah but added just in case 👍

2024-08-07 13:53 UTC, matan84 approved these changes
LGTM

2024-08-08 06:27 UTC, Tankilevitch approved these changes
love that, great job with the `CONTRIBUTING.md`

2024-08-08 06:28 UTC, merged