PORT-5176 Port-agent support for controlling the payload coming from port
port-labs/port-agent pull request #7
Opened 2023-11-09 13:56 UTC by yairsimantov20

Allowing the client to specify a mapping in the path `./control_the_payload_config.json` (can be changed with env) and modify the payload coming from port as he wish using jq expressions with the following syntax to the file

```
[ # Can have multiple mappings. Will use the first one it will find with enabled = True (Allows you to apply mapping over multiple actions at once)
  {
    "mapping": {
      "enabled": bool || JQ,
      "url": , # Optional. default is the incoming url from port
      "method": "'POST'", # Optional. default is post
      "headers": dict[str, JQ], # Optional. default is {}
      "body": ".body", # Optional. default is the whole payload incoming from main
      "query": {} # Optional. default is the whole payload incoming from main
    }
  }
]

2023-11-09 16:57 UTC, talsabagport reviewed
Nice work! 👍  Left small comments, and also need to add support in the [helm-chart](https://github.com/port-labs/helm-charts/tree/main/charts/port-agent)

2023-11-09 16:57 UTC, talsabagport commented on app/invokers/webhook_invoker.py
> +DEFAULT_INVOCATION_METHOD = "POST"
Move it to `consts.py`, and change it to `DEFAULT_HTTP_METHOD` :)

2023-11-09 16:57 UTC, talsabagport commented on app/invokers/webhook_invoker.py
> +            return jq.compile(expression).first(context)
compile is redundant when you don't reuse it, you can just use [first](https://github.com/doloopwhile/pyjq/blob/47b870ab7efaee260b621b879742d6c0636ff6cb/pyjq.py#L78), it also compiles

2023-11-13 16:06 UTC, talsabagport requested changes
Nice! Added few comments

2023-11-13 16:06 UTC, talsabagport commented on app/invokers/webhook_invoker.py
> +                for action_mapping in get_control_the_payload_config()
I think that in that case you read the config every webhook and not once in the agent initalization.

2023-11-13 16:06 UTC, talsabagport commented on app/invokers/webhook_invoker.py
> +        method = self._apply_jq_on_field(action.method, body, default_payload[0])
You can do even one liner with a loop over the fields and `getattr` from action

2023-11-13 16:06 UTC, talsabagport commented on app/invokers/webhook_invoker.py
> +        default_payload: tuple[str, None, dict, dict, dict] = (
Better to return a `dataclass` or `namedtuple`

2023-11-13 16:06 UTC, talsabagport commented on app/invokers/webhook_invoker.py
> +            url or str(invocation_method.get("url", "")),
I prefer this kind of logic to be in `_prepare_payload`

2023-11-13 16:06 UTC, talsabagport commented on app/invokers/webhook_invoker.py
> +            headers,
Consider sanitize the logged headers, because it might contains secrets, and take in account that the body can be huge.

2023-11-13 16:06 UTC, talsabagport commented on app/control_the_payload_config.json
> +      "ref": ".payload.properties.ref // .payload.action.invocationMethod.defaultRef // \"main\"",
What about `variables` and `port_payload`?

2023-11-13 21:10 UTC, yairsimantov20 commented on app/control_the_payload_config.json
> +      "ref": ".payload.properties.ref // .payload.action.invocationMethod.defaultRef // \"main\"",
just used the same logic from the gitlab code

2023-11-13 21:11 UTC, yairsimantov20 commented on app/invokers/webhook_invoker.py
> +            headers,
removed

2023-11-15 08:04 UTC, talsabagport approved these changes

2023-11-15 08:55 UTC, merged